### PR TITLE
dev(feat): add proxies support for Danbooru and Moebooru class && add documentation for proxies key-word argument

### PR DESCRIPTION
**Pull request by narugo1992**
## Description

Add proxy argument into `Danbooru` and `Moebooru` classes.

## Motivation and Context

In mainland China, the danbooru and other similar websites cannot be accessed directly, so a proxy is necessary.

## How Has This Been Tested?

I have tested based on the original `provisional_test.py`, the sample code is listed below.

## Code Examples (if appropriate):

```python
# encoding: utf-8
from __future__ import print_function
from pybooru import Danbooru
from pybooru import Moebooru

PROXIES = {  # change this to your own proxy, this will be passed into `requests.request` function without changes.
    "http": "socks5://192.168.56.1:16386",
    "https": "socks5://192.168.56.1:16386"
}

konachan = Moebooru("konachan", proxies=PROXIES)

kona_tags = konachan.tag_list(order='date')
print(konachan.last_call)
kona_post = konachan.post_list()
print(konachan.last_call)

lolibooru = Moebooru("lolibooru", proxies=PROXIES)

kona_tags = lolibooru.tag_list(order='date')
print(lolibooru.last_call)
kona_post = lolibooru.post_list()
print(lolibooru.last_call)

danbooru = Danbooru('danbooru', proxies=PROXIES)

dan_tags = danbooru.tag_list(order='name')
print(danbooru.last_call)
dan_post = danbooru.post_list(tags="computer")
print(danbooru.last_call)

print(danbooru.count_posts('nude'))

```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project (PEP-8).
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have readed CONTRIBUTING.md.

Yes, I have read your `.travis.yml`, this PR has been tested and linted as the scripts inside.

### CODE REVIEW

**Comment by LuqueDaniel** [comment]
Thanks for your contribution. And sorry for taking so long to review it.

As proxy is implemented in both classes `Danbooru` and `Moebooru` I think it would be better to implement it in `Pybooru` base class.

**Comment by narugo1992** [comment]
> Thanks for your contribution. And sorry for taking so long to review it.
> 
> As proxy is implemented in both classes `Danbooru` and `Moebooru` I think it would be better to implement it in `Pybooru` base class.

I agree. But the `request_args` are assigned in subclasses (`Danbooru` and `Moebooru`). Let me think about how to add proxy gracefully 😸

**Comment by narugo1992** [comment]
@LuqueDaniel The `proxies` has been moved to `PyBooru` class now.

**Review by LuqueDaniel — APPROVED** [review]
LGTM! Thanks for your contribution.

**Pull request merged**
